 - name: Install Certbot
   shell: |
      apt update
      apt install snapd -y
      snap install core
      snap refresh core
   become: yes

 - name: Install Certbot tool
   shell: snap install --classic certbot
   become: yes

 - name: Make Certbot executable
   shell: ln -s /snap/bin/certbot /usr/bin/certbot
   become: yes
   notify: 
      - Stop apache2

 - name: Install my certificates
   shell: certbot --apache --noninteractive --agree-tos --redirect -m adelek800@gmail.com -d 43kae.me
   become: yes
   notify:
      - Start apache2
